### ISSUE TITLE
MAL Access Control Interface not found

### ISSUE THREAD

**Issue by ebjorntvedt** [ccsdsmo/malc#1]
Hi,
The current version of the MAL implementation does not seem to provide any extension point for an application to provide an access control implementation as specified by the MAL recommended standard (CCSDS 521.0-B-2).

Will this feature be added?

**Comment by freyssin** [comment]
Hi,

```
 Such an API or SPI was not part of the initial objectives of the 
```

MAL/C prototype. However, the project is open and now it really make 
sense to add these access control functions. If you want to study this 
task we can possibly help you according to your needs

Regards, Andre.

Le 24/06/2016 à 15:14, ebjorntvedt a écrit :

> Hi,
> The current version of the MAL implementation does not seem to provide 
> any extension point for an application to provide an access control 
> implementation as specified by the MAL recommended standard (CCSDS 
> 521.0-B-2).
> 
> Will this feature be added?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/ccsdsmo/malc/issues/1, or mute the thread 
> https://github.com/notifications/unsubscribe/ARUdEScq0oFkrJs7UgVnFidFs5ja4KPiks5qO9gmgaJpZM4I9wOd.

## 

Need help for architecturing your distributed application?
Need professional support or additional development about Joram?

## mailto:joram@scalagent.com

Freyssinet Andre                   mailto:Andre.Freyssinet@scalagent.com
ScalAgent Distributed Technologies              http://www.scalagent.com
