### ISSUE TITLE
Missing function to encode the deregister argument

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#11]
Reading CCSDS 521.0-B-2 it seems that operations `register` and `deregister` do not take the same arguments. The first one use a `Subscription` while the second one uses a `List<Identifier>`.

The malc seems not conformant to this as it offers [functions](https://github.com/ccsdsmo/malc/blob/master/mal/include/mal.h#L262) for encoding the arguments for register operation, but nothing specific for `deregister`.

Furthermore, a [test](https://github.com/ccsdsmo/malc/blob/master/test/pubsub_app/src/pubsub_app_mysubscriber.c#L226) seems to be incorrect as it encodes a whole `Subscription`.

What is the correct way to do a `deregister` operation?

**Comment by freyssin** [comment]
True, it seems that the MAL/C interface needs more functions for encoding the arguments for deregister operation:

int mal_deregister_add_encoding_length(mal_encoder_t *encoder, mal_identifier_list_t *element, void *cursor);
int mal_deregister_encode(void *cursor, mal_encoder_t *encoder, mal_identifier_list_t *element);
int mal_deregister_decode(void *cursor, mal_decoder_t *decoder, mal_identifier_list_t **res);

The pubsub test doesn't implement a complete broker but it needs to be corrected.
