### ISSUE TITLE
Suspicious handling of maltcp headers flag

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#14]
While reading the code, I suspect a typo in the management of some maltcp header flags.

In one hand, I understand that the `authentication_id_flag` property of `maltcp_header_t` is set to true when authentication_id is NULL (Cf. https://github.com/ccsdsmo/malc/blob/master/maltcp/src/maltcp_header.c#L82)
But in the other hand, the authentication_id is taken into account for encoding when associated flag is positive, so true (Cf. https://github.com/ccsdsmo/malc/blob/master/maltcp/src/maltcp.c#L301)

As it is a significant issue, I suspect I misread something because unit tests are running. But my integration tests are failing here.

Can you give me your opinion?

**Comment by freyssin** [comment]
I think there is a misunderstanding about the [maltcp header flags](http://ccsdsmo.github.io/malc/mal_tcp/#maltcp-header). These flags prevent the transmission of the corresponding values when they are identical in all instances of the application. In this case the default values are retrieved through the maltcp header .

So if no default value are given in `maltcp_header_new` for `network_zone`, `session_name`, `domain` or `authentication_id`, the corresponding flag is set to true, and the corresponding parameter will be encoded in the message.

**Comment by gbonnefille** [comment]
Sorry, but I do not understand the referenced documentation.

>  `authentication_id`: Value of the *Authentication Id* field if it is not present in the MALTCP header.
>    If NULL the *Authentication Id* field should be present in the MALTCP header.

This part of documentation is inside the MALTCP header section. So, I understand `authentication_id` is the parameter given when building the MALTCP header. So, how can it be at the same time the default value and a NULL value?

**Comment by freyssin** [comment]
Sorry the documentation is not clear :-(, although there is some additional information in the `Configuration parameters` subsection.

There is use of the word 'MALTCP Header' to designate 2 different things: first the MALTCP header structure, second the header of MALTCP message (or PDU). The documentation should be rewritten like this: 

>  `authentication_id`: Default value of the *Authentication Id* field if it should not to be transmitted 
>  in the header of the MALTCP message (see section 3.3.3 of the MAL binding to TCP/IP transport 
>  blue book). If NULL the *Authentication Id* field should be present in the header of each MALTCP 
>  message.

Does this formulation suit you?

**Comment by gbonnefille** [comment]
I'm still unsure of my understanding.

Now, I understand that `mal_header_t` structure is only a container for default values of the header of the MAL TCP PDU. If related informations are not provided when creating a `mal_message_t`, then the encoder/decoder will use the values provided by the `mal_header_t`.

Nevertheless, it should still be possible to send/transport a message without optional informations like authentication_id, right? And the authentication_id_flag in the header of the header of the MAL TCP PDU is there to indicate whether or not the authentication_id is present.

(Sorry, this is certainly trivial, but I'm quite confused now :-) )

**Comment by freyssin** [comment]
There may have multiples behaviors but there are 2 normalized behaviors:
 - 1 - All application instances initialise the MAL/TCP with the same default value for authentication_id field.
 - 2 - No application instance initialises the MAL/TCP with a default value for authentication_id field.

In the first case the corresponding field is not set in the MAL TCP PDU by the sender, it will be set in the resulting MAL message by the receiver using the default value. In the second case the field is encoded in the MAL TCP PDU by the sender, and decoded by the receiver.

Other cases are possible but need to be studied carefully. Yes, the authentication_id_flag in the header of the MAL TCP PDU is there to indicate whether or not the authentication_id is present, but this can produce errors if no default value is set.
