### ISSUE TITLE
Possibly uninitialised value

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#15]
In my test, for a still unexplained reason, the provider returns a message without setting domain information (domain flag is set to 0). In this situation, the consumer SEGFAULT.

On the consumer end, `maltcp_header_t` was configured without defaulting value for domain.

Reading code, it appears that the consumer reuses directly the value of the field `domain` of the `maltcp_header_t`. But this information was never initialized and probably contains whatever value.

I feel that any field of  `maltcp_header_t` should be initialized to NULL in `maltcp_header_new` to avoid such situation.

PS: this partially refers to #14

**Comment by gbonnefille** [comment]
Please review https://github.com/gbonnefille/malc/tree/fix-maltcp-header-init

**Comment by freyssin** [comment]
True, while the use of these default values is protected by the corresponding flags during encoding, they are used without protection during decoding. We need to initialize each `maltcp_header_t` field even if the value is NULL.
