### ISSUE TITLE
Inconsistent message body

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#17]
On a complex environment, when a request operation is sent, the encoded body is inconsistent: for a null argument, the body is `01 41` while the expected result is `01 00`.

Reading code, it seems that the body buffer is used uninitialized. It is [allocated with a simple `malloc`](https://github.com/ccsdsmo/malc/blob/master/mal/src/mal_message.c#L102) and seems used as is for the bitfield.

A probable solution consist in using `calloc` instead of `malloc`, or zeroing at least the zone of the bitfield.

**Comment by gbonnefille** [comment]
What about:

~~~diff
diff --git a/malsplitbinary/src/malsplitbinary.c b/malsplitbinary/src/malsplitbinary.c
index f665cc5..a5cd723 100644
--- a/malsplitbinary/src/malsplitbinary.c
+++ b/malsplitbinary/src/malsplitbinary.c
@@ -99,6 +99,7 @@ void  malsplitbinary_encoder_cursor_init(void *cursor,
   malbinary_write_uvarinteger(bf_nb_bytes, bytes+offset);
 
   unsigned int bf_offset = offset + malbinary_var_uinteger_encoding_length(bf_nb_bytes);
+  memset(&bytes[bf_offset], 0, bf_nb_bytes);
   ((malsplitbinary_cursor_t *) cursor)->bitfield_ptr = &bytes[bf_offset];
   //body_offset
   int body_offset = bf_offset + bf_nb_bytes;
~~~

**Comment by freyssin** [comment]
Effectively the MAL message body is allocated trough a malloc, that is correct when using the MAL binary encoding but can lead to issues with the new split-binary encoding.
This fix seems correct, but to avoid other similary issues we will use calloc to allocate the MAL message body (as suggested in the first issue report).

**Comment by gbonnefille** [comment]
I suggested the patch in malsplitbinary.c because I realized I use this code directly, outside the scope of a mal_message (with a buffer I allocate myself). I considered that this is useful to ensure the bitfield is *always* initialized, whatever the allocation was.
