### ISSUE TITLE
Decoding MAL_LONG_LIST always return empty list

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#20]
It seems that the `mal_long_list` decoding function forgot to set the size of the decoded list:
https://github.com/ccsdsmo/malc/blob/master/mal/src/mal_long_list.c#L137

**Comment by gbonnefille** [comment]
Reading more codes, the bug seems also present in the following types:
* mal_boolean_list
* mal_double_list
* mal_duration_list
* mal_finetime_list
* mal_float_list
* mal_integer_list
* mal_octet_list
* mal_short_list
* mal_time_list
* mal_utinteger_list
* mal_ulong_list
* mal_uoctet_list
* mal_ushort_list

**Comment by freyssin** [comment]
Fixed.

**Comment by gbonnefille** [comment]
Thanks, it works now.
