### ISSUE TITLE
Encoding zero values

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#22]
While encoding an EntityKey containing 3 zeroes, I found a bug in the encoder.

When encoding a 0 as long, the resulting binary profile is 8 zeroes, while we are expecting a single one.

Looking at the code, I suspect the bug is in:

```
int malbinary_var_long_encoding_length(long value) {
  if (value > 0)
    return malbinary_var_ulong_encoding_length(2 * value);
  else
    return malbinary_var_ulong_encoding_length(-2 * value - 1);
}
```

I suspect the condition is wrong and should be `if (value >= 0)`. Currently, a 0 value induce a call to `malbinary_var_ulong_encoding_length` with a negative value.

**Comment by freyssin** [comment]
True, there is a similar issue with with short and integer encoding.
However I suspect an other issue in encode / decode corresponding code.

**Comment by freyssin** [comment]
In fact the calculation of the size of the buffer is overvalued but the computation of the offset after encoding seems correct. Finally the only consequence of this bug seems to be the allocation of a buffer too large for the message.

**Comment by gbonnefille** [comment]
Great news, thanks for analysis!

**Comment by freyssin** [comment]
The evaluation of the buffer size needed to encode an (unsigned) integer (16, 32 or 64 bits) is now correct.
