### ISSUE TITLE
Values of attribute's tag

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#24]
The values used for the attribute tag is not compliant with CCSDS RECOMMENDED STANDARD FOR  
MISSION OPERATIONS MESSAGE ABSTRACTION LAYER CCSDS 521.0-B-2.

It appears that they are all translated by one. For example, the [blob tag](https://github.com/ccsdsmo/malc/blob/master/malattributes/include/mal_attribute.h#L33) is valued to 0 (zero) while it is expected to be 1 (one).

**Comment by freyssin** [comment]
If I refer to section 5.2.2 of the MAL/TCP specification it seems that it is correct: "5.2.2	The field ‘Attribute Tag’ shall be assigned with the short form part of the attribute minus 1 so that the tag starts from zero.".

**Comment by gbonnefille** [comment]
It seems there is an error in the decoding process of the attribute tag. See work in progress on https://github.com/gbonnefille/malc/tree/fix-attribute-tag

**Comment by gbonnefille** [comment]
Branch updated to revise the mal attribute tag enc/dec functions and to fix the decoding of mal_attribute_t.

**Comment by gbonnefille** [comment]
Fixed by https://github.com/ccsdsmo/malc/pull/25
