### ISSUE TITLE
MALattributes error during instalation

### ISSUE THREAD

**Issue by a2147** [ccsdsmo/malc#35]
Hello, 

the installation hangs at the MALaatributes module. I tried to install all modules from the main folder (genmakeall command) and I got the error attached below. The same error I got when I try to install single module from the malattributes subfolder. Restarting the computer after installing prerequisites (GSL, CZMQ, ZPROJECT, ZEROMQ) didn't help. I'm using Ubuntu 17.04

Kind regards,
Arek

=== make
Making all in doc
make[1]: Entering directory '/home/a2147/Downloads/malc/malattributes/doc'
SKIPPING documentation generation and formatting (BUILD_DOC was not required and/or tools are missing)
make[1]: Leaving directory '/home/a2147/Downloads/malc/malattributes/doc'
make[1]: Entering directory '/home/a2147/Downloads/malc/malattributes'
  CC       src/src_libmalattributes_la-malattributes_private_selftest.lo
  CCLD     src/libmalattributes.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       src/src_malattributes_selftest-malattributes_selftest.o
src/malattributes_selftest.c:35:26: error: ‘malattributes_private_selftest’ undeclared here (not in a function)
     { "private_classes", malattributes_private_selftest },
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:984: recipe for target 'src/src_malattributes_selftest-malattributes_selftest.o' failed
make[1]: *** [src/src_malattributes_selftest-malattributes_selftest.o] Error 1
make[1]: Leaving directory '/home/a2147/Downloads/malc/malattributes'
Makefile:1056: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
ERROR in /home/a2147/Downloads/malc/malattributes

**Comment by freyssin** [comment]
Hi Arek,

Excuse me to insist but have you added all the projects in the list of known projects of zproject: 
> After installing 'zproject', the file 'zproject_known_projects.xml' (normally located in /usr/local/bin directory) has to be updated in order to contain the right versions of czmq, and the definition of new projects such as 'mal'

Regards,
Andre.

**Comment by a2147** [comment]
Hi Andre,

I have just tried on openSUSE 42.3 and double-checked that zproject_known_projects.xml file has been properly modified, but I have got exactly the same error. Should I somehow update zproject dependencies first before running ./genmakeall ?

Regards,
Arek

**Comment by freyssin** [comment]
Hi Arek,

This is strange. Could you try to start a cleanup (./genmakeall clean) before rebuilding the whole?

We have functional implementations on both CentOS7 and Suze (VM openSUSE 4.1.31), if that does not work, we will re-install from scratch on a new machine to check the full process.

Regards, Andre.

**Comment by gbonnefille** [comment]
If this can help, I did an experiment (unmaintained) around Travis-CI and Docker:
https://github.com/gbonnefille/malc/tree/travis-ci-docker

It can help to validate the building in a fresh environment.

**Comment by freyssin** [comment]
Hi Arek,

Thank to Guilhem and Docker we have found a soultion to this issue.

The problem seems to come from the use of recent versions of ZProject. We have make the necessary code changes in the project github and now it seems to work.

In addition, we now provide 2 Docker configuration files allowing to build the project on CentOS or OpenSuse.

Regards,
Andre.
