### ISSUE TITLE
TestArea XML file and associated code seem inconsistent

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#4]
While working from the XML file, we encounter strange behaviours. We think that the [XML file](https://github.com/ccsdsmo/malc/blob/master/xml/TestArea.xml) and parts of the _generated code_ are inconsistent. For example, the composite TestComposite is described with two fields (stringField and intField) while the code handles two more fields (floadField and doubleField, Cf. https://github.com/ccsdsmo/malc/blob/master/test/testarea/src/testarea_testservice_testcomposite.c#L33).

As the changes in the code seem to be inserted by the commit b7a3b92d2c7053133055589d91a47630c7fa39f9 we suspect the XML was changed but not committed.

Can you commit the XML associated to the code?

**Comment by freyssin** [comment]
The reference file to generate the TestArea area was in the C stubs generator project: https://github.com/ccsdsmo/stubgenerator_c/blob/master/test/src/main/xml/TestArea.xml.
Now, we have updated the TestArea XML definition in MAL/C project.
