### ISSUE TITLE
Double free on undelivered message

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#46]
It appears that mal_message can be destroyed by the caller of a send, but also by the `mal_actor_run`. In some situation, the mal_message is freed twice, which is wrong.

Exemple: test/submit_app

Who has the responsibility of destroying the mal_message?

**Comment by freyssin** [comment]
Currently the destroying of a received message is the responsibility of the callee, unless the handler method returns with an error code.
