### ISSUE TITLE
Mix of end-of-line encoding

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#5]
Reading at `splitbinary_encoder.c` in version 414420bf1d00b404f0bb029c75a749fdb35de0fc it seems there is a mix of end-of-line encoding:
- the header is in UNIX logic
- the rest of the file is in DOS logic

**Comment by freyssin** [comment]
Sorry, it is due to a bad configuration of Eclipse on Windows and this issue concerns a lot of files.
We will convert all files to Unix text file line delimiter.

**Comment by freyssin** [comment]
Normally now all files use the Unix text file line delimiter.

**Comment by gbonnefille** [comment]
The following command found some textual files still using CRLF end of line encoding, but they are MarkDown files and there is no mix.
`git ls-files | xargs file | grep CRLF`
