### ISSUE TITLE
Building the CentOS docker image fails

### ISSUE THREAD

**Issue by LeUlukai** [ccsdsmo/malc#54]
When building the docker image (as described in `ReadmeDocker.md`)
```
docker build -t malc-centos -f CentOSDockerfile .
```
the compilation for CZMQ process quits with
```
make[1]: Entering directory '/opt/czmq'
  CC       src/makecert-makecert.o
  CC       src/libczmq_la-zactor.lo
  CC       src/libczmq_la-zauth.lo
  CC       src/libczmq_la-zarmour.lo
  CC       src/libczmq_la-zbeacon.lo
  CC       src/libczmq_la-zcert.lo
  CC       src/libczmq_la-zcertstore.lo
  CC       src/libczmq_la-zchunk.lo
  CC       src/libczmq_la-zclock.lo
  CC       src/libczmq_la-zconfig.lo
  CC       src/libczmq_la-zdigest.lo
  CC       src/libczmq_la-zdir.lo
src/zdir.c: In function 'zdir_new':
src/zdir.c:201:9: error: 'readdir_r' is deprecated [-Werror=deprecated-declarations]
         int rc = readdir_r (handle, entry, &result);
         ^~~
In file included from src/../include/czmq_prelude.h:262,
                 from src/../include/czmq_library.h:24,
                 from src/../include/czmq.h:30,
                 from src/zdir.c:35:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
src/zdir.c:204:13: error: 'readdir_r' is deprecated [-Werror=deprecated-declarations]
             rc = readdir_r (handle, entry, &result);
             ^~
In file included from src/../include/czmq_prelude.h:262,
                 from src/../include/czmq_library.h:24,
                 from src/../include/czmq.h:30,
                 from src/zdir.c:35:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:1278: src/libczmq_la-zdir.lo] Error 1
```

The reason for this is that the `Dockerfile` uses `centos:latest` which recently have been upgraded to `centos:8`. At the time when the file was created/changed, I think it was `centos:7`. The new version of CentOS updated glibc to a version, which deprecates `readdir_r`.

In order to solve the problem, I see two options:
* Updating CZMQ; the current version does not use `readdir_r` anymore.
* Freeze the CentOS version in the `Dockerfile` to `centos:7`.

Which option do you prefer? The latter option worked for me; the compilation finished without any error. I could create a PR for this.

**Comment by freyssin** [comment]
In a first time it seems better to freeze the version of CentOS in the DockerFile.
In a second time we will perhaps upgrade the version of CentOS and CZMQ, but this will require a global validation of malc.
In any case it seems necessary to fix the version of CentOS to the version tested.
