### ISSUE TITLE
Adding a mal_actor_get_state

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#7]
The `mal_actor_t` stores a user data named [`state`](https://github.com/ccsdsmo/malc/blob/master/malactor/include/mal_actor.h#L43). But there is no mean to access this data later. Currently, the user code should keep references to both `mal_actor_t` and its own user data.

What about adding a `mal_actor_get_state` function? With such function, the user code can only keep a reference to `mal_actor_t` as single reference to its whole consumer/provider.

**Comment by freyssin** [comment]
It seems that this user data structure is returned in  all the actor's methods for processing messages.
However, there is no objection to adding a method in the interface to retrieve this structure from the actor's descriptor.
