### ISSUE TITLE
Avoid installing test includes and libraries

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#8]
When building the project with `./genmake all` all components are built and installed. But the test components are installed too, which seems not really useful.

How can we avoid such behaviour without iterating manually in each component?

I would suggest to evolve build scripts to:
* extract the install phase in order to be able to not install tests;
* add a `check` target in which tests are built and run.
The `check` target is common in autotools' world.

The use case would be:
~~~bash
./genmake all # build and install components
./genmake check # build and run tests, without installing them
~~~

**Comment by freyssin** [comment]
It seems to be a good idea, we have modified the scripts in order to add specific targets.
The corresponding target now corresponds to:
- ./genmake gen compile check
It is possible to add the corresponding shortcut.
